
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (2, "¿Puedes establecer la diferencia conceptual entre macroeconomía y microeconomía?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (3, "¿Si te convocara tu equipo preferido para planificar, organizar y dirigir un campo de deportes, aceptarías?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (4, "¿Te gustaría realizar una investigación que contribuyera a hacer más justa la distribución de la riqueza?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (5, "¿En un equipo de trabajo prefieres el rol de coordinador?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (6, "¿Dirigirías el área de importación y exportación de una empresa?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (7, "¿Te costearías tus estudios trabajando en una auditoría?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (8, "¿Te resultaría gratificante ser asesor contable en una empresa reconocida?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (9, "¿Sabes qué es el PRODUCTO INTERNO BRUTO?", 1, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (10, "¿Te ofrecerías para organizar la despedida de soltero(a) de uno de tus amigos?", 1, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (11, "¿Organizas tu dinero de manera que te alcance para todos tus gastos?", 1, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (12, "¿Distribuyes tu horario adecuadamente para poder hacer todo lo planeado?", 1, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (13, "¿Te resulta fácil coordinar un grupo de trabajo?", 1, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (14, "¿Si una gran empresa solicita un profesional como gerente comercial, te sentirías a gusto desempeñando ese rol?", 1, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (15, "¿Te gustaría trabajar con niños?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (16, "¿Elegirías una carrera cuyo instrumento de trabajo fuera la utilización de un idioma extranjero?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (17, "¿Dedicarías parte de tu tiempo para ayudar a personas de zonas vulnerables?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (18, "¿Te ofrecerías para explicar a tus compañeros un determinado tema que ellos no entendieran?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (19, "¿Pasarías varias horas leyendo un libro de tu interés?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (20, "¿Te interesan los temas relacionados al pasado y a la evolución del hombre?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (21, "¿Participarías en una investigación sobre la violencia en el fútbol (las barras bravas)?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (22, "¿Descubriste algún filósofo o escritor que haya expresado tus mismas ideas antes?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (23, "¿La libertad y la justicia son valores importantes en tu vida?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (24, "¿Lucharías por una causa justa hasta las últimas consecuencias?", 2, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (25, "¿Consideras importante que desde la escuela primaria se fomente la actitud crítica y la participación activa?", 2, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (26, "¿Preservar las raíces culturales de nuestro país te parece importante y necesario?", 2, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (27, "¿En una discusión entre amigos te ofreces como mediador?", 2, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (28, "¿Eres de los que defienden causas perdidas?", 2, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (29, "¿Te gustaría dirigir un proyecto de urbanización en tu barrio?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (30, "¿Te atrae armar rompecabezas?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (31, "¿Eres el que pone un toque de alegría en las fiestas?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (32, "¿Disfrutas trabajando con arcilla o plastilina?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (33, "¿Fuera de los horarios escolares, dedicas algún día a la semana a practicar algún deporte o actividad física?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (34, "¿Tolerarías empezar tantas veces como fuera necesario hasta obtener el logro deseado?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (35, "¿Cuando estás en un grupo de trabajo, te agrada producir ideas originales y que sean tenidas en cuenta?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (36, "¿Desearías que te regalaran algún instrumento musical para tu cumpleaños?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (37, "¿Harías el afiche para una campaña de prevención del SIDA?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (38, "¿Cuando eliges tu ropa o decoras un ambiente, tienes en cuenta la combinación de los colores, las telas o el estilo de los muebles?", 3, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (39, "¿Crees que los detalles son tan importantes como el todo?", 3, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (40, "¿Te gusta más el trabajo manual que el trabajo intelectual?", 3, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (41, "¿Harías un nuevo diseño de una prenda pasada de moda ante una reunión imprevista?", 3, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (42, "¿Dirigirías un grupo de teatro independiente?", 3, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (43, "¿Ante un llamado solidario, te ofrecerías para cuidar a un enfermo?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (44, "¿Escuchas atentamente los problemas que tienen tus amigos?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (45, "¿Convences fácilmente a otras personas sobre la validez de tus argumentos?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (46, "¿Te sentirías a gusto trabajando en un ambiente hospitalario?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (47, "¿Participarías en una campaña de prevención contra el virus AH1N1?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (48, "¿Te gustaría hacer un curso de primeros auxilios?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (49, "¿Acostumbras a leer revistas relacionadas con los últimos avances científicos y tecnológicos en el área de salud?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (50, "¿Te gustaría investigar sobre alguna nueva vacuna?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (51, "¿Te resulta interesante el estudio de las ciencias naturales?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (52, "¿Ante una emergencia epidémica, participarías en una campaña brindando tu ayuda?", 4, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (53, "¿Consideras que la salud pública debe ser prioritaria, gratuita y eficiente para todos?", 4, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (54, "¿Estarías dispuesto a renunciar a un momento placentero para ofrecer tu servicio como profesional?", 4, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (55, "¿Ayudas habitualmente a personas invidentes a cruzar la calle?", 4, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (56, "¿A una posición negativa siempre planteas un pensamiento positivo?", 4, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (57, "¿Te gustaría trabajar como profesional dirigiendo la construcción de una empresa hidroeléctrica?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (58, "¿Cuando eras pequeño, te interesaba saber cómo estaban construidos tus juguetes?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (59, "¿Cuando tienes que resolver un problema matemático, perseveras hasta encontrar la solución?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (60, "¿Entablas una relación casi personal con tu computador?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (61, "¿Te ofrecerías para colaborar como voluntario en la NASA?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (62, "¿Harías un curso para aprender a fabricar los instrumentos y/o piezas de las máquinas o aparatos con que trabajas?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (63, "¿Te incluirías en un proyecto nacional de desarrollo de la principal fuente de recursos de tu ciudad?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (64, "¿Cuando se daña un electrodoméstico, rápidamente te ofreces para arreglarlo o repararlo?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (65, "¿Te gustaría investigar científicamente sobre cultivos agrícolas?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (66, "¿Enviarías tu hoja de vida a una empresa automotriz que solicita gente para su área de producción?", 5, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (67, "¿Planificas detalladamente tus trabajos antes de empezar?", 5, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (68, "¿Crees que tus ideas son importantes y haces todo lo posible para ponerlas en práctica?", 5, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (69, "¿Trabajar con objetos te resulta más gratificante que trabajar con personas?", 5, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (70, "¿Eres exigente y crítico con tu equipo de trabajo?", 5, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (71, "¿Participarías en un grupo de defensa internacional dentro de alguna fuerza armada?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (72, "¿Te dedicarías a ayudar a personas accidentadas o atacadas por asaltantes?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (73, "¿Participarías como profesional en un espectáculo de acrobacia aérea?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (74, "¿Te gustaría participar para mantener el orden ante grandes desórdenes o catástrofes?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (75, "¿Aceptarías que las mujeres formaran parte de las fuerzas armadas bajo las mismas condiciones que los hombres?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (76, "¿Te interesan las actividades de mucha acción y de reacción rápida en situaciones imprevistas y de peligro?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (77, "¿Elegirías una profesión en la que tuvieras que estar algunos meses alejado de tu familia?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (78, "¿Aceptarías colaborar con el cumplimiento de las normas en lugares públicos?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (79, "¿Te gustaría realizar tareas auxiliares en un avión o aeronave, como izar velas, pintura y conservación de casco, arreglos de averías, conservación de motores?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (80, "¿Estás de acuerdo con la formación de un cuerpo de soldados profesionales?", 6, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (81, "¿Usar uniforme te hace sentir distinto, importante?", 6, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (82, "¿Crees que el país debe poseer la más alta tecnología armamentista, a cualquier precio?", 6, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (83, "¿Ante una situación de emergencia, actúas rápidamente?", 6, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (84, "¿Arriesgarías tu vida para salvar la vida de otro que no conoces?", 6, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (85, "¿Sabes responder qué significa ADN y ARN?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (86, "¿Te atrae investigar sobre los misterios del universo, por ejemplo, los agujeros negros?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (87, "¿Estás informado sobre nuevos descubrimientos que se están realizando sobre la Teoría del Big Bang?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (88, "¿Te gustaría crear nuevas técnicas para descubrir las patologías de algunas enfermedades a través del microscopio?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (89, "¿Te incluirías en un proyecto de investigación de los movimientos sísmicos y sus consecuencias?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (90, "¿Te gustaría trabajar en un laboratorio mientras estudias?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (91, "¿Te radicarías en una zona agrícola-ganadera para desarrollar tus actividades como profesional?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (92, "¿Formarías parte de un equipo de trabajo orientado a la preservación de la flora y la fauna en extinción?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (93, "¿Aceptarías hacer una práctica rentada en una industria de productos alimenticios, en el sector de control de calidad?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (94, "¿Visitarías un observatorio astronómico para conocer en sección el funcionamiento de los aparatos?", 7, 1);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (95, "¿El trabajo individual te resulta más rápido y efectivo que el trabajo grupal?", 7, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (96, "¿Te interesan más los misterios de la naturaleza que los secretos de la tecnología?", 7, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (97, "¿Te inhibes al entrar a un lugar nuevo con gente desconocida?", 7, 0);
INSERT INTO pregunta (id_pregunta, pregunta, id_materia, tipo) VALUES (98, "¿Tienes interés por saber cuáles son las causas que determinan ciertos fenómenos, aunque saberlo no incida en tu vida?", 7, 0);